//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiMexicanApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int Id { get; set; }
        public int IdTypeMeal { get; set; }
        public string Name { get; set; }
        public string Img { get; set; }
        public string ImgOutline { get; set; }
        public string ImgBlack { get; set; }
    
        public virtual TypeMeal TypeMeal { get; set; }
    }
}
